# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    services:
      neo4j35:
        image: neo4j:3.5
        ports:
          - 8687:7687
          - 8474:7474
        env:
          NEO4J_AUTH: neo4j/test
      neo4j41:
        image: neo4j:3.1
        ports:
          - 9687:7687
          - 9474:7474
        env:
          NEO4J_AUTH: neo4j/test
      neo4j42:
        image: neo4j:4.2
        ports:
          - 10687:7687
          - 10474:7474
        env:
          NEO4J_AUTH: neo4j/test
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f test_requirements.txt ]; then pip install -r test_requirements.txt; fi
    - name: Test with pytest
      run: |
        python -m pytest
